name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  windows:
    name: windows-release
    runs-on: windows-latest

    strategy:
      matrix:
        config: [Release]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup premake
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Create Solution file
        run: premake5.exe vs2022

      - name: Build app
        run: msbuild /m /p:Configuration=${{matrix.config}} .

      - name: Create release zip
        run: Copy-Item LICENSE,Data -Destination "bin/${{matrix.config}}-windows/PuruPuru" && Compress-Archive bin/${{matrix.config}}-windows/PuruPuru ${{matrix.config}}.zip

      - name: Publish
        id: Publish
        uses: softprops/action-gh-release@v1
        with:
          name: PuruPuru v0.1.1
          tag_name: v0.1.1
          body_path: CHANGELOG.md
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          files: |
            ${{matrix.config}}.zip