name: Publish for Ubuntu

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Ubuntu-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config: [release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Setup premake
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"

      - name: Install dependencies
        run: sudo apt update && sudo apt upgrade -y && sudo apt install libxcursor-dev libxrandr-dev libxinerama-dev libgtk-3-dev -y
            
      - name: Compile & Link project
        run: premake5 gmake2 && make config=${{matrix.config}}

      - name: Create archive
        run: tar --create --file=Ubuntu_${{matrix.config}}.tar LICENSE Data imgui.ini -C bin/Release-linux/PuruPuru PuruPuru && ls

      - name: Publish
        id: Publish
        uses: softprops/action-gh-release@v1
        with:
          name: PuruPuru v0.1.5
          tag_name: v0.1.5
          body_path: CHANGELOG.md
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          files: |
            Ubuntu_${{matrix.config}}.tar